language: java
env:
  global:
    - secure: "AAYX5LFSNHrRXgyQmpRr3j3OVbzM3iDcYd0o9NERgNw64VQeKWdd6BMy0Bc3\nJ4Q1pXKjPpS81GigToDuyQwSkt8GKp/WDMzhiY0NP8oBQmlXI9Q2HRweIqaS\nRwrtPf1AckG8r51/4MEZsmfUHPZjhN7LVjBWUaLTgLCjw2tvrt4="
    - secure: "I+5a0w6RZkcpWYkhFXlK3mhJWvlsJDIgNqtDq1WmHcbaYzfDmgtx8u3oxfIr\nHt5r4tAl9/O483HOyNfcjGLCRmD4IdMPIFCfobPKpOVzKr82cJDGZg4tnoPP\nL/KdFucgZUE/EkAZA5Qc5k5xeLCmpFVJqygAzztn49S7Bkw+Hr8="
    - secure: "WFJNplyqiFPmTuSpVOYe00HIy5hzrbx2TcSQoRZ63K9S2CxjCTitbj4o24jo\n3LZJ1FSKrGLuMLQWvRxqZMbHirjRbgZdHBRE0Je8jwCW0rYHF6+YHKNs8Wt/\nN/ss0wzntRXp4q9HZT5vLPD+i0Xa0Up5RWUE+ASK80/i7Pfr+qA="
notifications:
  email:
    on_failure: change
jdk:
  - openjdk6
install: mvn -DskipTests=true -e install
script: mvn -e -Dskip.code.coverage=false -Dmaven.javadoc.skip=true -Dsource.skip=true verify
after_success: mvn sonar:sonar -Dsonar.sourceEncoding=UTF-8 -Dsonar.core.codeCoveragePlugin=jacoco -Dsonar.dynamicAnalysis=reuseReports -Dsonar.host.url=http://sonar.codereligion.com -Dsonar.jdbc.url=$SONAR_DB_URL -Dsonar.jdbc.username=$SONAR_DB_USER -Dsonar.jdbc.password=$SONAR_DB_PASSWORD
